### ISSUE TITLE
byteswapping check is broken

### ISSUE THREAD

**Issue by swolchok** [milend/chmap#1]
https://github.com/milend/chmap/blob/main/cheadermap/src/binary/header.rs#L86 should read `magic != MAGIC_NATIVE_ENDIAN && magic != magic_swapped`. (if you want to write the more straightforward `magic != MAGIC_NATIVE_ENDIAN && magic_swapped != MAGIC_NATIVE_ENDIAN`, then you need to patch line 90 to read `    let swap_bytes = magic_swapped == MAGIC_NATIVE_ENDIAN;` as well)

**Comment by milend** [comment]
Thanks @swolchok - fixed by e84328c!
